updating circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,39 +1,48 @@
+version: 2
 jobs:
-  build_and_deploy:
+  build:
     docker:
-      - image: 'eu.gcr.io/cars-restful-api/node-app'
+      - image: eu.gcr.io/cars-restful-api/node-app:latest
     steps:
       - checkout
-      - cloudrun/init
-      - cloudrun/build:
-          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
-      - cloudrun/deploy:
-          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
-          platform: managed
-          region: eu-west3
-          service-name: example-service
-          unauthenticated: true
-      - run:
-          command: >
-            # A simple example of how a deployed managed service could be
-            verified or further tested.
+      - run: echo "A first hello"
 
-            # This step will send request our "API" and fail if there is
-            unexpected output.
-
-            GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
-
-            if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
-              echo "Result is unexpected"
-              echo 'Result: '
-              curl -s "$GCP_DEPLOY_ENDPOINT"
-              exit 1;
-            fi
-          name: Test managed deployed service.
-orbs:
-  cloudrun: circleci/gcp-cloud-run@1.0.2
-version: 2.1
-workflows:
-  build_and_deploy_to_managed_workflow:
-    jobs:
-      - build_and_deploy
+#jobs:
+#  build_and_deploy:
+#    docker:
+#      - image: 'eu.gcr.io/cars-restful-api/node-app'
+#    steps:
+#      - checkout
+#      - cloudrun/init
+#      - cloudrun/build:
+#          tag: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
+#      - cloudrun/deploy:
+#          image: 'gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}'
+#          platform: managed
+#          region: eu-west3
+#          service-name: example-service
+#          unauthenticated: true
+#      - run:
+#          command: >
+#            # A simple example of how a deployed managed service could be
+#            verified or further tested.
+#
+#            # This step will send request our "API" and fail if there is
+#            unexpected output.
+#
+#            GCP_API_RESULTS=$(curl -s "$GCP_DEPLOY_ENDPOINT")
+#
+#            if [ "$GCP_API_RESULTS" != "Hello World!" ]; then
+#              echo "Result is unexpected"
+#              echo 'Result: '
+#              curl -s "$GCP_DEPLOY_ENDPOINT"
+#              exit 1;
+#            fi
+#          name: Test managed deployed service.
+#orbs:
+#  cloudrun: circleci/gcp-cloud-run@1.0.2
+#version: 2.1
+#workflows:
+#  build_and_deploy_to_managed_workflow:
+#    jobs:
+#      - build_and_deploy
